FROM node:18.19.0-alpine

WORKDIR /app
COPY src ./src
COPY package*.json ./
COPY .sequelizerc .
COPY .env.development .env
COPY docker/development-entrypoint.sh .

RUN yarn install --frozen-lockfile
RUN yarn global add sequelize-cli
RUN yarn global add nodemon
RUN chmod 755 development-entrypoint.sh
CMD ["node", "./src/index.js"]

EXPOSE 3011


