version: '3'

services:
  backend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
        - "3000:3000"
    environment:
        - NODE_ENV=development
        - PORT=3000
        - COOKIE_EXPIRATION_HOURS=24
        - SQL_USERNAME=emre
        - SQL_HOST=postgres
        - SQL_DATABASE_NAME=insider
        - SQL_PASSWORD=123
    depends_on:
        db-init:
            condition: service_completed_successfully
    links:
        - postgres

  db-init:
      build:
          context: ..
          dockerfile: ./docker/db-init/Dockerfile
      environment:
          - NODE_ENV=development
          - SQL_USERNAME=emre
          - SQL_HOST=postgres
          - SQL_DATABASE_NAME=insider
          - SQL_PASSWORD=123
      depends_on:
          postgres:
              condition: service_healthy
      links:
          - postgres

  postgres:
    image: postgres:16
    environment:
        - POSTGRES_USER=emre
        - POSTGRES_PASSWORD=123
        - POSTGRES_DB=insider
    ports:
        - "5432:5432"
    volumes:
        - postgres:/var/lib/postgresql/data
    healthcheck:
        test: "pg_isready --username=$$POSTGRES_USER --dbname=$$POSTGRES_DB"
        interval: 5s
        timeout: 3s
        retries: 5

volumes:
    postgres:
        driver: local
